### ISSUE TITLE
Including and repeating content in specific volumes

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/braille-css-spec#23]
Add a section that describes how to include and repeat certain content at the beginning or end of specific volumes, using the "named flow" feature. The section belongs under either [Volumes](http://snaekobbi.github.io/braille-css-spec/#h2_volumes) or [Out-of-Flow Positioning](http://snaekobbi.github.io/braille-css-spec/#h2_out-of-flow-positioning).

**Comment by bertfrees** [comment]
Example: to repeat content in each volume, use the "flow(..., all)" within the @begin rule: 

```css
#titlepage {
  flow: preliminary;
}
@volume {
  @begin {
    content: flow(preliminary, all);
  }
}
```
Elements can not be styled based on in which volume they appear (just like elements
can't be styled based on the page type on which they appear). This would cause problems
anyway because of the fact that elements can be split across volumes. The solution is to
style elements based on their named flow:

```css
@volume {
  @begin {
    content: flow(preliminary, all);
  }
}
@volume:first {
  @begin {
    content: none;
  }
}
toc {
  flow: normal preliminary;
  ...
}
toc:flow(preliminary) {
  ...
}
```

**Comment by bertfrees** [comment]
This is now supported in the specification, except that the `all` keyword is called `document`, the `flow` property must be a single `<ident>`, and there is no `:flow(...)` pseudo-class. Instead of
```css
toc {
  flow: normal preliminary;
  ...
}
toc:flow(preliminary) {
  ...
}
```
you would now use:
```css
toc {
  ...
}
toc::duplicate {
  flow: preliminary;
  ...
}
```

See http://snaekobbi.github.io/braille-css-spec/#h3_named-flows.
